# Site settings
title: Yaroslav Heriatovych
email: Yarikx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal thoughts about Android Development, Functional Programming and RxJava.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yarikx.github.io" # the base hostname & protocol for your site
twitter_username: yarikx
github_username:  yarikx

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-gist

gist:
  noscript: false

